"""empty message

Revision ID: 147ed72cc7c1
Revises: 667c80deaa21
Create Date: 2020-04-14 09:04:30.270737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147ed72cc7c1'
down_revision = '667c80deaa21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movies', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
